"use client";

import { ComponentType, useEffect, useRef, useState } from "react";
import { useTheme } from "next-themes";
import { ChevronLeft, Dumbbell, Flame, Footprints, Home, ImagePlus, Map, Play, Search, Shield, SunMoon, Trophy, Upload, UserRound, Users, Video, X } from "lucide-react";
import type { Coordinates } from "./workout-map";

type Privacy = "Todos" | "Amigos" | "Oculto";
type Tab = "feed" | "map" | "challenges" | "profile";
type LocationIntent = "map" | "start";
type Post = { id: string; author: string; initials: string; title: string; description: string; workout: string; challenge?: string; duration: string; distance: string; media?: string; mediaType?: "image" | "video"; createdAt: string };
type WorkoutMapProps = { position: Coordinates; showAthletes: boolean };
type Props = { WorkoutMap: ComponentType<WorkoutMapProps> };

const starterPosts: Post[] = [
  { id: "seed-1", author: "Luana Martins", initials: "LM", title: "5K antes do sol nascer", description: "Começar o dia em movimento muda tudo. Quem vem amanhã?", workout: "Corrida", challenge: "10K de Agosto", duration: "31 min", distance: "5,02 km", createdAt: "há 18 min" },
  { id: "seed-2", author: "Caio Alves", initials: "CA", title: "Costas + bíceps", description: "Mais uma sessão concluída no desafio da semana.", workout: "Musculação", challenge: "Força em 21 dias", duration: "54 min", distance: "—", createdAt: "há 1 h" },
];
const defaultPosition = { lat: -4.9372, lng: -37.9748 };
const challenges = [{ name: "10K de Agosto", goal: "Corra 10 km esta semana", progress: 62, people: 184 }, { name: "Força em 21 dias", goal: "Complete 12 treinos de força", progress: 42, people: 96 }, { name: "Movimento diário", goal: "Treine 5 dias seguidos", progress: 80, people: 312 }];
const workoutOptions = [
  { name: "Corrida", description: "Ruas, parque ou esteira", icon: <Footprints size={22} /> }, { name: "Caminhada", description: "No seu ritmo", icon: <Footprints size={22} /> }, { name: "Trail running", description: "Corrida em trilha", icon: <Footprints size={22} /> }, { name: "Ciclismo", description: "Pedal ao ar livre", icon: <Play size={20} fill="currentColor" /> }, { name: "Mountain bike", description: "Pedal em trilha", icon: <Play size={20} fill="currentColor" /> }, { name: "Ciclismo indoor", description: "Spinning e bike indoor", icon: <Play size={20} fill="currentColor" /> },
  { name: "Natação", description: "Piscina ou águas abertas", icon: <Flame size={21} /> }, { name: "Remo", description: "Remo indoor ou na água", icon: <Flame size={21} /> }, { name: "Surf", description: "Mar e ondas", icon: <Flame size={21} /> }, { name: "Stand up paddle", description: "Equilíbrio na água", icon: <Flame size={21} /> }, { name: "Triatlo", description: "Multiesporte", icon: <Trophy size={21} /> },
  { name: "Musculação", description: "Força e academia", icon: <Dumbbell size={21} /> }, { name: "Treino funcional", description: "Movimento e condicionamento", icon: <Dumbbell size={21} /> }, { name: "Cross training", description: "Alta intensidade", icon: <Dumbbell size={21} /> }, { name: "Calistenia", description: "Peso corporal", icon: <Dumbbell size={21} /> }, { name: "Pilates", description: "Controle e mobilidade", icon: <Dumbbell size={21} /> }, { name: "Yoga", description: "Corpo e mente", icon: <Dumbbell size={21} /> }, { name: "Alongamento", description: "Mobilidade e recuperação", icon: <Dumbbell size={21} /> }, { name: "Dança", description: "Ritmo e movimento", icon: <Flame size={21} /> },
  { name: "Futebol", description: "Campo, society ou futsal", icon: <Trophy size={21} /> }, { name: "Basquete", description: "Quadra", icon: <Trophy size={21} /> }, { name: "Vôlei", description: "Quadra ou areia", icon: <Trophy size={21} /> }, { name: "Tênis", description: "Raquete e quadra", icon: <Trophy size={21} /> }, { name: "Beach tennis", description: "Raquete na areia", icon: <Trophy size={21} /> }, { name: "Padel", description: "Raquete e parede", icon: <Trophy size={21} /> }, { name: "Handebol", description: "Quadra", icon: <Trophy size={21} /> },
  { name: "Boxe", description: "Técnica e condicionamento", icon: <Flame size={21} /> }, { name: "Muay thai", description: "Arte marcial tailandesa", icon: <Flame size={21} /> }, { name: "Jiu-jitsu", description: "Luta de solo", icon: <Flame size={21} /> }, { name: "Judô", description: "Arte marcial japonesa", icon: <Flame size={21} /> }, { name: "Karatê", description: "Arte marcial", icon: <Flame size={21} /> }, { name: "Taekwondo", description: "Arte marcial coreana", icon: <Flame size={21} /> }, { name: "MMA", description: "Artes marciais mistas", icon: <Flame size={21} /> },
  { name: "Escalada", description: "Indoor ou ao ar livre", icon: <Trophy size={21} /> }, { name: "Esqui", description: "Neve e montanha", icon: <Trophy size={21} /> }, { name: "Skate", description: "Rua ou pista", icon: <Trophy size={21} /> }, { name: "Outro", description: "Registrar outra atividade", icon: <Dumbbell size={21} /> },
];

export function PulseApp({ WorkoutMap }: Props) {
  const { resolvedTheme, setTheme } = useTheme();
  const [tab, setTab] = useState<Tab>("feed"); const [privacy, setPrivacy] = useState<Privacy>("Todos"); const [active, setActive] = useState(false); const [position, setPosition] = useState<Coordinates>(defaultPosition); const [error, setError] = useState(""); const [showComposer, setShowComposer] = useState(false); const [showStartSetup, setShowStartSetup] = useState(false); const [workout, setWorkout] = useState("Corrida"); const [posts, setPosts] = useState<Post[]>(starterPosts); const [xp, setXp] = useState(700); const [locationIntent, setLocationIntent] = useState<LocationIntent | null>(null); const [locating, setLocating] = useState(false); const [locationError, setLocationError] = useState(""); const watchRef = useRef<number | null>(null);
  useEffect(() => { const hydration = window.setTimeout(() => { const saved = localStorage.getItem("pulse-state"); if (saved) { try { const data = JSON.parse(saved); if (data.posts) setPosts(data.posts); if (data.xp) setXp(data.xp); } catch { /* Ignore stale storage. */ } } }, 0); return () => window.clearTimeout(hydration); }, []);
  useEffect(() => { localStorage.setItem("pulse-state", JSON.stringify({ posts, xp })); }, [posts, xp]);
  useEffect(() => () => { if (watchRef.current !== null) navigator.geolocation?.clearWatch(watchRef.current); }, []);
  function requestLocation(intent: LocationIntent) { setError(""); setLocationError(""); setLocationIntent(intent); if (!navigator.geolocation) { setLocationError("Este navegador não oferece geolocalização. Para usar o mapa e iniciar atividades, abra o PULSE em um navegador compatível."); return; } setLocating(true); navigator.geolocation.getCurrentPosition((current) => { setPosition({ lat: current.coords.latitude, lng: current.coords.longitude }); setLocating(false); setLocationIntent(null); if (intent === "map") setTab("map"); else setShowStartSetup(true); }, (locationFailure) => { setLocating(false); setLocationError(locationFailure.code === locationFailure.PERMISSION_DENIED ? "A localização foi bloqueada. Permita o acesso nas configurações do navegador para continuar." : "Não foi possível obter sua localização agora. Verifique o GPS e tente novamente."); }, { enableHighAccuracy: true, timeout: 12000, maximumAge: 10000 }); }
  function openStartSetup() { requestLocation("start"); }
  function openMap() { requestLocation("map"); }
  function startTraining() { setError(""); setShowStartSetup(false); setTab("map"); if (!navigator.geolocation) return; const success = (current: GeolocationPosition) => { setPosition({ lat: current.coords.latitude, lng: current.coords.longitude }); setActive(true); }; const fail = () => { setActive(false); setError("A localização deixou de estar disponível. O treino não está sendo compartilhado."); }; navigator.geolocation.getCurrentPosition(success, fail, { enableHighAccuracy: true, timeout: 8000, maximumAge: 0 }); watchRef.current = navigator.geolocation.watchPosition(success, fail, { enableHighAccuracy: true, maximumAge: 4000 }); }
  function stopTraining() { if (watchRef.current !== null) { navigator.geolocation?.clearWatch(watchRef.current); watchRef.current = null; } setActive(false); setShowComposer(true); }
  function publish(form: { title: string; description: string; workout: string; media?: string; mediaType?: "image" | "video" }) { const challenge = challenges.find((c) => form.workout === "Corrida" ? c.name === "10K de Agosto" : c.name === "Força em 21 dias")?.name; const minutes = Math.max(1, Math.round((Date.now() % 3600000) / 60000)); setPosts((current) => [{ id: crypto.randomUUID(), author: "Você", initials: "YO", title: form.title, description: form.description, workout: form.workout, challenge, duration: `${minutes} min`, distance: form.workout === "Corrida" ? "3,4 km" : "—", media: form.media, mediaType: form.mediaType, createdAt: "agora" }, ...current]); setXp((value) => value + 100); setShowComposer(false); setTab("feed"); }
  const level = Math.floor(xp / 500) + 1; const levelProgress = xp % 500;
  return <main className="app-shell"><header className="topbar"><div className="wordmark">PUL<b>SE</b></div><button className="icon-btn" onClick={() => setTheme(resolvedTheme === "dark" ? "light" : "dark")} aria-label="Alternar tema"><SunMoon size={18} /></button></header>{tab === "feed" && <Feed posts={posts} onStart={openStartSetup} />}{tab === "map" && <MapScreen WorkoutMap={WorkoutMap} position={position} privacy={privacy} setPrivacy={setPrivacy} active={active} start={openStartSetup} stop={stopTraining} error={error} />}{tab === "challenges" && <Challenges posts={posts} />}{tab === "profile" && <Profile xp={xp} level={level} progress={levelProgress} posts={posts} />}<nav className="nav"><NavButton label="Feed" icon={<Home size={18}/>} active={tab === "feed"} onClick={() => setTab("feed")}/><NavButton label="Mapa" icon={<Map size={18}/>} active={tab === "map"} onClick={() => tab === "map" ? undefined : openMap()}/><button className="start-nav" onClick={active ? stopTraining : openStartSetup} aria-label={active ? "Parar treino" : "Escolher treino"}>{active ? <X size={21}/> : <Play size={21} fill="currentColor"/>}</button><NavButton label="Desafios" icon={<Trophy size={18}/>} active={tab === "challenges"} onClick={() => setTab("challenges")}/><NavButton label="Perfil" icon={<UserRound size={18}/>} active={tab === "profile"} onClick={() => setTab("profile")}/></nav>{showStartSetup && <StartWorkout workout={workout} setWorkout={setWorkout} privacy={privacy} setPrivacy={setPrivacy} onClose={() => setShowStartSetup(false)} onStart={startTraining} />}{showComposer && <Composer initialWorkout={workout} onClose={() => setShowComposer(false)} onPublish={publish} />}{locationIntent && <LocationGate locating={locating} error={locationError} onRetry={() => requestLocation(locationIntent)} onClose={() => { if (!locating) { setLocationIntent(null); setLocationError(""); } }} />}</main>;
}
function NavButton({ label, icon, active, onClick }: { label: string; icon: React.ReactNode; active: boolean; onClick: () => void }) { return <button className={active ? "active" : ""} onClick={onClick}>{icon}<span>{label}</span></button>; }
function LocationGate({ locating, error, onRetry, onClose }: { locating: boolean; error: string; onRetry: () => void; onClose: () => void }) { return <div className="modal-backdrop" style={{alignItems:"center",padding:20}} role="dialog" aria-modal="true" aria-label="Localização necessária"><section style={{width:"min(100%, 360px)",padding:"25px 22px 20px",border:"1px solid var(--line)",borderRadius:24,background:"var(--background)",textAlign:"center"}}><div style={{width:46,height:46,display:"grid",placeItems:"center",margin:"0 auto 14px",borderRadius:16,background:"color-mix(in srgb, var(--lime) 28%, var(--surface))",color:"var(--lime-dark)"}}><Map size={22}/></div><h2 style={{margin:0,fontSize:20,letterSpacing:"-.7px"}}>{locating ? "Encontrando você" : "Localização necessária"}</h2><p style={{minHeight:39,margin:"8px 0 19px",color:"var(--muted)",fontSize:13,lineHeight:1.45}}>{locating ? "Estamos solicitando sua localização para abrir o mapa." : error}</p>{locating ? <div style={{width:27,height:27,margin:"0 auto 10px",border:"3px solid var(--line)",borderTopColor:"var(--lime-dark)",borderRadius:"50%",animation:"location-spin .75s linear infinite"}} aria-label="Obtendo localização"/> : <button className="primary" onClick={onRetry}>Tentar novamente</button>}<button style={{marginTop:12,border:0,background:"transparent",color:"var(--muted)",fontSize:12,fontWeight:700}} onClick={onClose} disabled={locating}>Cancelar</button></section></div> }
function StartWorkout({ workout, setWorkout, privacy, setPrivacy, onClose, onStart }: { workout: string; setWorkout: (value: string) => void; privacy: Privacy; setPrivacy: (value: Privacy) => void; onClose: () => void; onStart: () => void }) {
  const [query, setQuery] = useState("");
  const normalizedQuery = query.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase();
  const matchingWorkouts = workoutOptions.filter((option) => `${option.name} ${option.description}`.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().includes(normalizedQuery));
  return <section className="start-workout-screen" aria-label="Preparar treino"><header className="start-workout-head"><button className="icon-btn" onClick={onClose} aria-label="Voltar"><ChevronLeft size={21}/></button><strong>Iniciar atividade</strong><span/></header><div className="start-workout-content"><div className="start-workout-intro"><span>SEU PRÓXIMO PULSO</span><h1>O que você vai fazer?</h1><p>Escolha uma atividade e comece quando estiver pronto.</p></div><label className="workout-search"><Search size={18}/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar esporte, luta ou exercício" aria-label="Buscar atividade" />{query && <button type="button" onClick={() => setQuery("")} aria-label="Limpar busca"><X size={16}/></button>}</label><div className="workout-results">{query ? `${matchingWorkouts.length} atividade${matchingWorkouts.length === 1 ? "" : "s"}` : "Todas as atividades"}</div><div className="workout-options" role="radiogroup" aria-label="Tipo de treino">{matchingWorkouts.map((option) => <button key={option.name} className={`workout-option ${workout === option.name ? "selected" : ""}`} onClick={() => setWorkout(option.name)} role="radio" aria-checked={workout === option.name}><i>{option.icon}</i><span><b>{option.name}</b><small>{option.description}</small></span><em/></button>)}{matchingWorkouts.length === 0 && <p className="workout-empty">Nenhuma atividade encontrada. Tente outro termo.</p>}</div></div><footer className="start-workout-footer"><div className="start-privacy"><div><Shield size={17}/><span><b>Visibilidade no mapa</b><small>{privacy === "Oculto" ? "Só você verá a sua localização" : "Quem pode ver você treinando"}</small></span></div><div className="privacy compact">{(["Todos", "Amigos", "Oculto"] as Privacy[]).map((item) => <button key={item} className={privacy === item ? "selected" : ""} onClick={() => setPrivacy(item)}>{item}</button>)}</div></div><button className="primary" onClick={onStart}><Play size={18} fill="currentColor"/> Começar {workout.toLowerCase()}</button></footer></section>;
}
function Feed({ posts, onStart }: { posts: Post[]; onStart: () => void }) { return <><section className="hero"><h1>Seu treino puxa a comunidade.</h1><p>Comece agora e apareça no mapa com a sua galera.</p><div className="streak"><Flame size={16} fill="currentColor"/> 4 dias em sequência</div></section><section className="section"><div className="section-head"><h2>Agora na comunidade</h2><button onClick={onStart}>Iniciar treino</button></div>{posts.map((post) => <PostCard post={post} key={post.id}/>)}</section></> }
function PostCard({ post }: { post: Post }) { return <article className="post"><div className="post-head"><div className={`avatar ${post.author === "Você" ? "me" : ""}`}>{post.initials}</div><div><div className="post-name">{post.author}</div><div className="post-time">{post.createdAt}</div></div></div><p className="post-desc"><strong>{post.title}</strong><br/>{post.description}</p>{post.media ? post.mediaType === "video" ? <video className="media" controls src={post.media}/> : <img className="media" src={post.media} alt="Registro do treino"/> : <div className="media-placeholder"><Dumbbell size={38}/></div>}<div className="post-meta"><span className="pill">{post.workout}</span><span className="pill muted">{post.duration}</span>{post.distance !== "—" && <span className="pill muted">{post.distance}</span>}{post.challenge && <span className="pill">{post.challenge}</span>}</div></article> }
function MapScreen({ WorkoutMap, position, privacy, setPrivacy, active, error }: Omit<WorkoutMapProps, "showAthletes"> & { WorkoutMap: ComponentType<WorkoutMapProps>; privacy: Privacy; setPrivacy: (p: Privacy) => void; active: boolean; start?: () => void; stop?: () => void; error: string }) {
  const isHidden = privacy === "Oculto";
  const [noticeState, setNoticeState] = useState<"visible" | "leaving" | "hidden">("visible");
  useEffect(() => { const timer = window.setTimeout(() => setNoticeState("leaving"), 10000); return () => window.clearTimeout(timer); }, []);
  return <><div className="map-wrap"><WorkoutMap position={position} showAthletes/><div className="map-overlay"><div className="live-chip"><span className="dot"/>{active ? "TREINO AO VIVO" : "ATLETAS TREINANDO"}</div><div className="live-chip"><Users size={14}/>{isHidden ? "Você invisível" : privacy === "Todos" ? "18 perto" : "3 amigos"}</div></div><div className="map-controls"><div className="privacy">{(["Todos", "Amigos"] as Privacy[]).map((item) => <button key={item} className={privacy === item ? "selected" : ""} onClick={() => setPrivacy(item)}>{item}</button>)}</div></div></div>{noticeState !== "hidden" && <aside className={`map-location-notice ${noticeState === "leaving" ? "leaving" : ""}`} onAnimationEnd={() => noticeState === "leaving" && setNoticeState("hidden")}><Shield size={15}/><p>Sua localização exata só fica ativa enquanto este treino estiver em andamento.</p><button type="button" onClick={() => setNoticeState("leaving")} aria-label="Fechar aviso"><X size={16}/></button></aside>}{error && <p className="location-note">{error}</p>}</> }
function Challenges({ posts }: { posts: Post[] }) { return <section className="section"><div className="section-head"><h2>Seus desafios</h2><span className="pill">3 ativos</span></div>{challenges.map((challenge) => <article className="challenge" key={challenge.name}><div className="challenge-top"><div><h3>{challenge.name}</h3><p>{challenge.goal}</p></div><Trophy size={19} color="var(--lime-dark)"/></div><div className="progress"><i style={{width:`${challenge.progress}%`}}/></div><div className="challenge-footer"><span>{challenge.progress}% completo</span><span>{challenge.people} atletas</span></div></article>)}<div className="section-head" style={{marginTop:24}}><h2>Posts nos desafios</h2></div>{posts.filter((post) => post.challenge).map((post) => <PostCard key={post.id} post={post}/>)}</section> }
function Profile({ xp, level, progress, posts }: { xp:number; level:number; progress:number; posts:Post[] }) { return <section className="profile"><div className="profile-card"><div className="avatar me">YO</div><h1>Você</h1><p>@pulse.runner · Russas, CE</p><div className="level"><div><span>NÍVEL</span><br/><strong>{level}</strong></div><div><span>{progress} / 500 XP para o próximo nível</span><div className="progress" style={{width:150}}><i style={{width:`${progress / 5}%`}}/></div></div></div><div className="stats"><div><b>{xp}</b><span>XP total</span></div><div><b>{posts.filter(p=>p.author === "Você").length}</b><span>treinos</span></div><div><b>4</b><span>melhor streak</span></div></div></div><div className="section" style={{padding:"25px 0"}}><div className="section-head"><h2>Conquistas</h2></div><div className="challenge"><div className="challenge-top"><div><h3>Primeiro pulso</h3><p>Publique seu primeiro treino</p></div><Flame size={19} color="var(--lime-dark)"/></div></div></div></section> }
function Composer({ initialWorkout, onClose, onPublish }: { initialWorkout: string; onClose: () => void; onPublish: (value: { title: string; description: string; workout: string; media?: string; mediaType?: "image" | "video" }) => void }) { const [title,setTitle]=useState(""); const [description,setDescription]=useState(""); const [workout,setWorkout]=useState(initialWorkout); const [media,setMedia]=useState<string>(); const [mediaType,setMediaType]=useState<"image"|"video">(); const [validation,setValidation]=useState(""); function choose(event: React.ChangeEvent<HTMLInputElement>, type:"image"|"video") { const file=event.target.files?.[0]; if(file){setMedia(URL.createObjectURL(file));setMediaType(type);} } function submit(){if(!title.trim()){setValidation("Dê um título ao seu treino antes de publicar.");return;}onPublish({title,description,workout,media,mediaType});} return <div className="modal-backdrop"><section className="composer"><div className="handle"/><button className="icon-btn" style={{float:"right",marginTop:-5}} onClick={onClose} aria-label="Fechar"><X size={18}/></button><h2>Treino concluído!</h2><p className="sub">Seu treino vale +100 XP quando for publicado.</p><label className="field">Título</label><input className="input" value={title} onChange={e=>setTitle(e.target.value)} placeholder="Ex.: Corrida no Parque do Cocó"/><label className="field">Descrição</label><textarea className="textarea" value={description} onChange={e=>setDescription(e.target.value)} placeholder="Como foi seu treino?"/><label className="field">Tipo de treino</label><select className="select" value={workout} onChange={e=>setWorkout(e.target.value)}>{workoutOptions.map((option) => <option key={option.name}>{option.name}</option>)}</select><div className="upload-grid"><label className="upload">{mediaType === "image" && media ? <img className="preview" src={media} alt="Prévia"/> : <><ImagePlus size={19}/><span>Adicionar foto</span></>}<input accept="image/*" type="file" onChange={e=>choose(e,"image")}/></label><label className="upload">{mediaType === "video" && media ? <Video size={24}/> : <><Video size={19}/><span>Adicionar vídeo</span></>}<input accept="video/*" type="file" onChange={e=>choose(e,"video")}/></label></div>{validation && <p style={{color:"#e35d4e",fontSize:12}}>{validation}</p>}<button className="primary" onClick={submit}><Upload size={17}/> Publicar treino · +100 XP</button></section></div> }
